
services:
  mariadb:
    image: mariadb:11.8
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: Passord
      MARIADB_DATABASE: kartverket
      MARIADB_USER: appuser
      MARIADB_PASSWORD: werHTG123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "appuser", "-pwerHTG123"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s


  web:
    build:
      context: .
      dockerfile: FirstWebApplication/Dockerfile
    container_name: firstwebapplication
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080;https://+:8081
      ASPNETCORE_Kestrel__Certificates__Default__Path: /app/aspnetapp.pfx
      ASPNETCORE_Kestrel__Certificates__Default__Password: DevPassword123
      ASPNETCORE_HTTPS_PORT: 8081
      ConnectionStrings__OurDbConnection: "Server=mariadb;Port=3306;Database=kartverket;User=appuser;Password=werHTG123"
    depends_on:
      mariadb:
        condition: service_healthy
    ports:
      - "8000:8080"
      - "8001:8081"
    volumes:
      - data_protection_keys:/keys
    entrypoint: ["/bin/sh", "-c", "mkdir -p /keys && chmod -R 777 /keys && chmod 644 /app/aspnetapp.pfx && dotnet FirstWebApplication.dll"]
    user: "0:0"
    networks:
      - appnet
    restart: on-failure

networks:
  appnet:
    driver: bridge

volumes:
  mysql_data:
  data_protection_keys: