services:
  mariadb:
    image: mariadb:11.4
    container_name: mariadbcontainer
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=kartverket_app
      - MARIADB_USER=kartuser
      - MARIADB_PASSWORD=Passord
      - MARIADB_ROOT_PASSWORD=Passord
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 -uroot -pPassord --silent || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 15s
  
  
  
  firstwebapplication:
    image: ${DOCKER_REGISTRY-}firstwebapplication
    build:
      context: .
      dockerfile: FirstWebApplication/Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8000:8080"   # HTTP
      - "8001:8081"   # HTTPS
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:8080;https://0.0.0.0:8081
      - ConnectionStrings__OurDbConnection=Server=mariadbcontainer;Port=3306;Database=kartverket_app;User=kartuser;Password=Passord;TreatTinyAsBoolean=false;

volumes:
  mariadb_data:
