// <auto-generated />
using FirstWebApplication.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstWebApplication.Migrations
{
    // Knytter denne databasen til ApplicationContext
    [DbContext(typeof(ApplicationContext))] 
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        // Her beskrives databasen  
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Litt teknisk info om versjon og database innstillinger
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            // Gjør at id-felt teller opp automatisk 
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            // Lager tabell i databasen som heter "Advices"
            modelBuilder.Entity("FirstWebApplication.Models.AdviceDto", b =>
                {
                    // Tabellen har tre kolonner:
                    // AdviceId = id-nummer 
                    // Title = tittel (må fylles ut)
                    // Description = beskrivelse (må fylles ut)

                    b.Property<int>("AdviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdviceId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("AdviceId");

                    b.ToTable("Advices");
                });
#pragma warning restore 612, 618
        }
    }
}
